kind: StorageClass

apiVersion: storage.k8s.io/v1

metadata:

  name: aws-efs1

provisioner: lw-course/aws-efs

---

kind: PersistentVolumeClaim

apiVersion: v1

metadata:

  name: efs-drupal
  annotations:

    volume.beta.kubernetes.io/storage-class: "aws-efs1"

spec:

  accessModes:

    - ReadWriteMany

  resources:

    requests:

      storage: 10Gi

---

kind: PersistentVolumeClaim

apiVersion: v1

metadata:

  name: efs-postgresql

  annotations:

    volume.beta.kubernetes.io/storage-class: "aws-efs1"

spec:

  accessModes:

    - ReadWriteMany

  resources:

    requests:

      storage: 10Gi
