apiVersion: v1
kind: Service
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  selector:
    app: drupal
    env: frontend
  type: LoadBalancer
  ports:
  - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  selector:
     matchLabels:
       app: drupal
       env: frontend
  template:
    metadata:
      labels: 
        app: drupal
        env: frontend
    spec: 		
      containers:
      - name: drupal
        image: drupal:8-apache
        ports:
          - containerPort: 80
            name: drupal

