apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: drupal
spec:
  selector:
    app: drupal
    env: backend
  ports:
    - port: 5432
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: drupal
spec:
  selector:
     matchLabels:
       app: drupal
       env: backend  
  template:
    metadata:
      labels: 
        app: drupal
        env: backend
    spec: 		
      containers:
      - name: postgres
        image: postgres:10
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: rootpwd 
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: mypd-postgres
        ports:
          - containerPort: 5432
            name: postgres
      volumes:
        - name: mypd-postgres
          persistentVolumeClaim:
            claimName: efs-postgresql
